#!/bin/sh
# vired: the visual raw editor
# copyleft: pancake at nopcode dot org @ 2009

if [ -n "$1" ]; then
  $0 | red -n $@
  exit 0
fi

ttyset=`stty -g`
stty -echo -icanon min 1

getstr() {
  stty icanon echo
  read A
  echo $A
  stty -icanon -echo
}

while : ; do
  echo "!clear"
  case $P in
  'd') echo '!echo X | red -s $BLOCK | rasm2 -o $OFFSET -d -' ;;
  *)   echo x ;;
  esac
  A=`dd if=/dev/tty count=1 bs=1 2>/dev/null`
  case $A in
  'j') echo "s+16" ;;
  'k') echo "s-16" ;;
  'h') echo "s-1" ;;
  'l') echo "s+1" ;;
  'q') stty $ttyset; exit ;;
  'b') printf 'b '>/dev/tty; echo b `getstr` ;;
  'w') printf 'w '>/dev/tty; echo w `getstr` ;;
  's') printf 's '>/dev/tty; echo s `getstr` ;;
  ':') printf ': '>/dev/tty; echo `getstr`; read A ;;
  '?') echo '?'; read A ;;
  '+') echo "b+1" ;;
  '-') echo "b-1" ;;
  '*') echo "b+16" ;;
  '/') echo "b-16" ;;
  'p') if [ -n "$P" ]; then P=''; else P=d; fi ;;
  esac
done
